# Generated by Django 5.1.15 on 2026-09-06 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('reforme', 'Réforme'), ('innovation', 'Innovation'), ('initiative', 'Initiative'), ('resultat', 'Résultat'), ('interview', 'Interview'), ('conseil', 'Conseil')], default='reforme', max_length=20, verbose_name='Catégorie')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
